=== CMSM-VCU/ansys-micromechanics/input_schema/input.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "$id": "ansysmicro/input",
    "title": "Ansys Micromechanics Input",
    "description": "Input deck defining a micromechanics test case",
    "type": "object",
    "properties": {
        "caseId": {
            "description": "The unique identifier for a test case",
            "type": "integer",
            "minimum": 1
        },
        "caseDescription": {
            "description": "The description of a test case",
            "type": "string"
        },
        "units": {
            "description": "The set of units used for a test case (documentation only, no effect on simulation)",
            "type": "object",
            "properties": {
                "length": {
                    "type": "string"
                },
                "mass": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            },
            "required": ["length", "mass", "time"]
        },
        "boundaryConditions": {
            "description": "The parameters defining the boundary conditions",
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "enum": ["Okereke"]
                }
            },
            "required": ["kind"]
        },
        "loading": {
            "description": "The loading parameters for a test case",
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "enum": ["tensor", "displacement"]
                },
                "tensors": {
                    "type": "array",
                    "description": "The strain tensors to be applied to the RVE in sequence",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 3,
                        "items": {
                            "type": "array",
                            "minItems": 3,
                            "maxItems": 3,
                            "items": {
                                "anyOf": [{ "type": "number" }, { "type": "null" }]
                            }
                        }
                    }
                },
                "magnitudeMultiplier": {
                    "type": "number",
                    "description": "The scalar by which to multiply the strain tensors",
                    "default": 1
                },
                "labels": {
                    "type": "array",
                    "description": "Optional labels corresponding with each load case. Must be same number of labels as load cases",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "expectedProperties": {
                    "type": "array",
                    "description": "The list of effective properties to be reported for each test. Either one list for all tests or one list for each test (n_lists == 1 or n_lists == n_tests). A list containing 'all' will be replaced with all available properties.",
                    "minItems": 1,
                    "items": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "pattern": "^([EGv][123][123]|all)$",
                            "examples": ["E11", "G12", "v31", "all"]
                        }
                    }
                },
                "directions": {
                    "description": "[Deprecated]",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "pattern": "^-?[123][123]$",
                        "examples": ["11", "12", "-23", "31"]
                    }
                },
                "normalMagnitude": {
                    "type": "number",
                    "description": "[Deprecated] The magnitude of loading for all normal tests, units depending on kind"
                },
                "shearMagnitude": {
                    "type": "number",
                    "description": "[Deprecated] The magnitude of loading for all shear tests, units depending on kind"
                }
            },
            "required": ["kind", "expectedProperties"],
            "oneOf": [
                {
                    "properties": { "kind": { "enum": ["tensor"] } },
                    "required": ["tensors", "magnitudeMultiplier"]
                },
                {
                    "properties": { "kind": { "enum": ["displacement"] } },
                    "required": ["directions", "normalMagnitude", "shearMagnitude"]
                }
            ]
        },
        "materials": {
            "description": "The list of materials and their properties",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "materialIndex": {
                        "description": "The index number for a material",
                        "type": "integer",
                        "minimum": 1
                    },
                    "materialName": {
                        "description": "The name of a material (documentation only, no effect on simulation",
                        "type": "string"
                    },
                    "materialType": {
                        "description": "The directionality of a material",
                        "type": "string",
                        "enum": ["isotropic", "orthotropic", "anisotropic"]
                    },
                    "elasticModuli": {
                        "description": "The elastic moduli of a material in the three principal directions",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "exclusiveMinimum": 0.0
                        }
                    },
                    "shearModuli": {
                        "description": "The shear moduli of a material in the three principal planes: 1-2, 2-3, 3-1",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "exclusiveMinimum": 0.0
                        }
                    },
                    "poissonsRatios": {
                        "description": "The poisson's ratios of a material in the three principal planes: 1-2, 2-3, 3-1",
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": -1.0,
                            "maximum": 0.5
                        }
                    },
                    "density": {
                        "description": "The volumetric density of a material. Only used in PD cases (currently).",
                        "type": "number",
                        "exclusiveMinimum": 0.0
                    }
                },
                "oneOf": [
                    {
                        "properties": {
                            "materialType": { "enum": ["isotropic"] },
                            "elasticModuli": {
                                "minItems": 1,
                                "maxItems": 1
                            },
                            "poissonsRatios": {
                                "minItems": 1,
                                "maxItems": 1
                            },
                            "shearModuli": false
                        },
                        "required": [
                            "materialIndex",
                            "materialName",
                            "materialType",
                            "elasticModuli",
                            "poissonsRatios"
                        ]
                    },
                    {
                        "properties": {
                            "materialType": { "enum": ["orthotropic"] },
                            "elasticModuli": {
                                "minItems": 3,
                                "maxItems": 3
                            },
                            "shearModuli": {
                                "minItems": 3,
                                "maxItems": 3
                            },
                            "poissonsRatios": {
                                "minItems": 3,
                                "maxItems": 3
                            }
                        },
                        "required": [
                            "materialIndex",
                            "materialName",
                            "materialType",
                            "elasticModuli",
                            "shearModuli",
                            "poissonsRatios"
                        ]
                    }
                ]
            },
            "minItems": 1
        },
        "mesh": {
            "description": "The data defining the RVE mesh",
            "type": "object",
            "properties": {
                "elementType": {
                    "type": "string",
                    "description": "The element type to use in the mesh",
                    "default": "SOLID185"
                },
                "nodeFileRelativePath": {
                    "type": "string",
                    "description": "The path to the file containing node data (relative to this input file)"
                },
                "elementFileRelativePath": {
                    "type": "string",
                    "description": "The path to the file containing element data (relative to this input file)"
                },
                "csysFileRelativePath": {
                    "type": "string",
                    "description": "The path to the file containing element coordinate system data (relative to this input file)"
                },
                "domainSideLength": {
                    "type": "number",
                    "description": "[Deprecated] The side length of the cubic domain, centered on the origin"
                },
                "elementSpacing": {
                    "type": "number",
                    "description": "[Deprecated] The element edge length in FEA cases, the grid spacing in PD cases",
                    "exclusiveMinimum": 0.0
                },
                "locationsWithId": {
                    "description": "[Deprecated] The locations ordered as [xloc, yloc, zloc, materialIndex]",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": [
                            {
                                "type": "number",
                                "description": "x coordinate"
                            },
                            {
                                "type": "number",
                                "description": "y coordinate"
                            },
                            {
                                "type": "number",
                                "description": "z coordinate"
                            },
                            {
                                "type": "integer",
                                "description": "Material index",
                                "minimum": 1
                            }
                        ],
                        "minItems": 4,
                        "additionalItems": false
                    },
                    "minItems": 0
                }
            },
            "oneOf": [
                {
                    "required": [
                        "domainSideLength",
                        "elementSpacing",
                        "locationsWithId"
                    ]
                },
                {
                    "required": [
                        "elementType",
                        "nodeFileRelativePath",
                        "elementFileRelativePath"
                    ]
                }
            ]
        },
        "runnerOptions": {
            "description": "The options for configuring the test runner",
            "type": "object",
            "additionalProperties": true
        }
    },
    "required": [
        "caseId",
        "caseDescription",
        "units",
        "boundaryConditions",
        "loading",
        "materials",
        "mesh"
    ]
}

=== CMSM-VCU/ansys-micromechanics/examples/single_fiber_tensors_ex02.json
{
    "caseId": 111113,
    "caseDescription": "Single fiber verification case, using strain tensors. Fewer load cases for faster debugging. Example of orthotropic material input",
    "units": {
        "length": "micrometer",
        "mass": "gram",
        "time": "second"
    },
    "boundaryConditions": {
        "kind": "Okereke"
    },
    "loading": {
        "kind": "tensor",
        "labels": ["x normal", "zx shear"],
        "magnitudeMultiplier": 0.001,
        "tensors": [
            [
                [1, 0, 0],
                [0, null, 0],
                [0, 0, null]
            ],
            [
                [0, 0, 0],
                [0, 0, 0],
                [1, 0, 0]
            ]
        ],
        "expectedProperties": [["E11", "v12", "v13"], ["G31"]]
    },
    "materials": [
        {
            "materialIndex": 1,
            "materialName": "Polypropylene",
            "materialType": "isotropic",
            "elasticModuli": [1.31e6],
            "poissonsRatios": [0.43],
            "density": 903e-15
        },
        {
            "materialIndex": 2,
            "materialName": "Glass fiber",
            "materialType": "orthotropic",
            "elasticModuli": [7.3e7, 7.3e6, 7.3e6],
            "shearModuli": [3.8e7, 3.8e6, 3.8e6],
            "poissonsRatios": [0.2, 0.3, 0.3],
            "density": 1450e-15
        }
    ],
    "mesh": {
        "elementType": "SOLID186",
        "nodeFileRelativePath": "./meshes/fiber_corners_ex01.node",
        "elementFileRelativePath": "./meshes/fiber_corners_ex01.elem"
    },
    "runnerOptions": {
        "nproc": 2,
        "jobname": "single_fiber_ex02",
        "run_location": "./ex02_working_dir"
    }
}
